const PREFIX = `WEATHER_FORECAST:`;
export const GET_LOCATIONS = `${PREFIX}GET_LOCATIONS`;
export const GET_WEATHER_DAYS = `${PREFIX}GET_WEATHER_DAYS`;
export const SET_LOADING = `${PREFIX}SET_LOADING`;
export const SET_LOCATIONS = `${PREFIX}SET_LOCATIONS`;
export const SET_WEATHER_DAYS = `${PREFIX}SET_WEATHER_DAYS`;